services:
  - type: web
    name: tds-data-analyst
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: ./entrypoint.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
    healthCheckPath: /summary
    autoDeploy: true
